CREATE TABLE IF NOT EXISTS game_apis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_api_name VARCHAR(50) UNIQUE NOT NULL,
    status TINYINT(1) NOT NULL DEFAULT 1,
    is_seamless BOOLEAN NOT NULL DEFAULT TRUE,
    extra_info JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);