CREATE TABLE IF NOT EXISTS game_apis (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_api_name VARCHAR(50) UNIQUE NOT NULL,
    extra_info JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);