CREATE TABLE IF NOT EXISTS game_api_credentials (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    game_api_id VARCHAR(50) UNIQUE NOT NULL,
    extra_info JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
